#baseURL = "www.knowprocess.com"
baseURL = "beta.knowprocess.com"
languageCode = "en-gb"
title = "KnowProcess"
themesDir = "themes"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Passionate about Business Automation and all things Digital."
    meta_og_title = "KnowProcess"
    meta_og_type = "website"
    meta_og_url = "https://knowprocess.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Passionate about Business Automation and all things Digital."
    meta_twitter_card = "summary"
    meta_twitter_site = "@knowprocess"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3


[[menu.main]]
    name = "History"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
