name: CD
on:
  push:
    branches:
      - master
      - 'releases/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.92.2"
          extended: true

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./public/*
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_DIR }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
     
      #- name: Deploy
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    personal_token: ${{ secrets.TOKEN }}
      #    external_repository: <username>/<username>.github.io
      #    publish_dir: ./public
          #   keep_files: true
      #    user_name: <username>
      #    user_email: <username@email.com>
      #    publish_branch: master
        #   cname: example.com
